### PR TITLE
Add a virtual keyboard to edit settings

### PR DESCRIPTION
**Pull request by anxuae**
Add an optional virtual keyboard for editing settings with a touch-screen

### CODE REVIEW

**Comment by werdeil** [comment]
I didn't find a way to make the keyboard visible: I only get the following line in the log but no keyboard visible
`[ WARNING ] pygame_vkeyboard.vkeyboard: Computed layout height outbound target surface, reducing key_size to 42px`

Any idea?

**Comment by anxuae** [comment]
Did you enable de virtual keyboard in the config?

**Comment by werdeil** [comment]
Yes I have

**Comment by werdeil** [comment]
Found why it didn't worked on my setup: need to click on the field to make it appear.

Maybe we can add the "RETURN" key as a way to make it appear?

I'm merging this anyway.

**Pull request merged**
