### PR TITLE
Prepare migration to pygame-menu v3

### PR DESCRIPTION
**Pull request by anxuae**
Preparation for the new major release of pygame-menu 3.0.0 which will be release on 1st May.
This is just the beginning, for discussion and improvements.

Documentation is here: https://pygame-menu.readthedocs.io

### CODE REVIEW

**Comment by anxuae** [comment]
Capture d’écran 2020-05-07 à 17 35 39
Capture d’écran 2020-05-07 à 17 35 48
Capture d’écran 2020-05-07 à 17 35 56
Capture d’écran 2020-05-07 à 17 36 16

**Comment by anxuae** [comment]
Example of v3 menu with monospaced font. Colors to be discussed of course ;-)

**Comment by enricofusco** [comment]
is the new version ready?
how can i update everything?

**Comment by anxuae** [comment]
Hi @enricofusco,
The version 2.0.0 is not yet finished, I hope that it can be released soon.
If you need it, you can clone the git repo, then install the developing version following those instructions: https://github.com/pibooth/pibooth/blob/master/docs/dev.rst

**Comment by werdeil** [comment]
I capitalize one menu entry that wasn't yet.

4 comments to start: 
- I have changed the menu theme (white on green is not visible on my screen (see screenshot), switching to `THEME_DARK` is working.
Capture d’écran 2020-05-11 à 09 46 51
- We no longer have a different color for submenus is it intended? I use to find it useful to know if an escape would lead me to close the settings or not.
- There is a merge conflict to correct, I let you look into it as it is your changes.
- I liked the fact that the version wasn't shown as a menu entry but in the title in the previous version, here it seems like something not reachable and buggy.

**Comment by werdeil** [comment]
And why did you remove the robot font from available fonts?

**Comment by anxuae** [comment]
> I have changed the menu theme (white on green is not visible on my screen (see screenshot), switching to THEME_DARK is working.
White is ok on my PC but ok for DARK (personally I think it too sad)

> We no longer have a different color for submenus is it intended? I use to find it useful to know if an escape would lead me to close the settings or not.

What do you think about the blue theme for second menu? (note that ESC leading to back or close the menu is now indicated in the right corner: you have a cross or an arrow)

> There is a merge conflict to correct, I let you look into it as it is your changes.

Merge conflict is closed

> I liked the fact that the version wasn't shown as a menu entry but in the title in the previous version, here it seems like something not reachable and buggy.

I feel the menu bar too large with the version number inside. What about an `About` submenu with some details about the project and the version number.

> And why did you remove the roboto font from available fonts?

Probably because they are not used, I will re-add them

**Comment by anxuae** [comment]
I'm trying to find some example of color themes for UI:

**black background & colors**


**white background & colors**

**Comment by anxuae** [comment]
Capture d’écran 2020-05-14 à 17 46 20
Capture d’écran 2020-05-14 à 17 46 30
Capture d’écran 2020-05-14 à 17 47 51
Capture d’écran 2020-05-14 à 17 48 04

**Comment by anxuae** [comment]
@werdeil what do you think about those menus?

**Comment by werdeil** [comment]
Need to test on my side, as the rendering was not the same on it. Il like both but the bold font of the titles looks too big no?

**Comment by anxuae** [comment]
Yes, I have try by reducing the font size, but maybe bold font should not be used?
I let you decide after you test it.

**Comment by anxuae** [comment]
I can remove the white theme, this was just an example

**Pull request merged**
