### PR TITLE
Add Swedish translation

### PR DESCRIPTION
**Pull request by esnil**
This pull request adds Swedish translation.

### CODE REVIEW

**Comment by esnil** [comment]
Is there something more I should do in order to get this merged in?

@anxuae
@nsty

**Comment by nsty** [comment]
I'm not a maintainer. Waiting for a pull myself.

**Comment by esnil** [comment]
> I'm not a maintainer. Waiting for a pull myself.

Ok, thanks for replying. Do you know any more maintainers than @anxuae ?

**Comment by DJ-Dingo** [comment]
I can see you already put it in the "Help us to add new languages!!" thread https://github.com/pibooth/pibooth/issues/90
So you properly have to wait for the next update, before it will be added

**Review by werdeil — APPROVED** [review]

**Comment by esnil** [comment]
Thank you @werdeil and thank you for maintaining. We have had a lot of fun with this software :)

**Pull request merged**
