### PR TITLE
split menu label on 2 columns if more than 5 (ie add plugins)

### PR DESCRIPTION
**Pull request by sravel**
For best visual if try to split menu like this:
Default:
Menu5
Default with 1 plugin:
Menu6
With 1 plugin format with my pull request
Menu6-format
With 2 plugins:
menu7

### CODE REVIEW

**Comment by werdeil** [comment]
I'm not very fan of the two columns layout, I've two questions:
- @anxuae is the two columns layout really an option on pygame_menu, there is no example in the gallery. If it is the case why don't we use it for setting -- value instead of monospaces.
- how does it work when accessing to the settings with the two button (how do we switch to the second column?).

**Comment by sravel** [comment]
I test with button and selection go to the first element of second column at the end of first
I think on small screen it is better to use two columns instead of scroll bar like this
scroll

**Comment by werdeil** [comment]
I'm more fan of the scroll bar

**Comment by anxuae** [comment]
> @anxuae is the two columns layout really an option on pygame_menu, there is no example in the gallery. If it is the case why don't we use it for setting -- value instead of monospaces.

The two columns (and more if you want) in a feature of `pygame-menu`. But you can't separate the text from the dynamic area in two different columns.

**Comment by sravel** [comment]
Hello, 
So you want to add or not? This is your app so you have the final choice.

**Comment by anxuae** [comment]
No matter to me, I let @werdeil to decide

**Comment by werdeil** [comment]
As said before

> I'm more fan of the scroll bar

But keep this PR opened, if someone want to upvote it.

**Comment by sravel** [comment]
otherwise I can see to add it as an option in the config file (deactivate by default)

**Comment by werdeil** [comment]
Hey @sravel I don't know if you've seen but you have added your xml in the PR. I don't think you want to add it. This happens because the PR is from your master to ours, so each time you push to your master it will go in this PR.

The best way to avoid this is to do PR from a branch instead of master. For me the best way for you it to do the following:
- create a branch split_menu `git branch split_menu`
- switch to this branch: `git checkout split_menu`
- remove the xml and commit it
- push the branch to github `git push` will tell you what to add to allow this push
- change the base branch of this PR: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request

Tell me if it worked.

**Comment by sravel** [comment]
Yes sorry.
I try but I can't change the pull request branch on my fork.
I think solution is to create new PR with the good on.
I append option to allow a split or not.

**Pull request closed without merging**
