### PR TITLE
Fix #290: Add implementation of libcamera driver

### LINKED ISSUE #290: Add support for libcamera/picamera2 (PiOS bullseye and Arducam)
hello
Could someone add the support for the arducam pivariety camera please
this camera use libcamera to work. 
she is compatible with openCV
my imx298 modele : https://www.arducam.com/docs/cameras-for-raspberry-pi/pivariety/16mp-imx298-pivariety-motorized-focus-camera-module/
installation of librairie : https://www.arducam.com/docs/cameras-for-raspberry-pi/pivariety/how-to-access-and-program-the-pivariety-camera-using-command-line-python-opencv-and-gstreamer
thanks for the help

### PR DESCRIPTION
**Pull request by anxuae**
Close #290

### CODE REVIEW

**Review by werdeil — APPROVED** [review]
Ok for the changes at least it shall not have impact on current use, as we cannot test it.

**Comment by CaffeinatedFunctionality** [comment]
How can I help with this? I just bought the 64mp camera from arducam and need this to work with it

**Comment by anxuae** [comment]
We are waiting for the official release of [picamera2](https://github.com/raspberrypi/picamera2).

**Comment by CollinBardini** [comment]
@CaffeinatedFunctionality @anxuae
I made a [fork to support the 64mp arducam ](https://github.com/CollinBardini/pibooth)using the picamera2 library. It works, but I think I can improve the preview performance. If you give it a shot, let me know what you think!

**Comment by joerno** [comment]
> @CaffeinatedFunctionality @anxuae I made a [fork to support the 64mp arducam ](https://github.com/CollinBardini/pibooth)using the picamera2 library. It works, but I think I can improve the preview performance. If you give it a shot, let me know what you think!

I tried your changes but it doesnt work for me. First I had to add one argument to this function under `elif rpi_cam_2_proxy::`
`close_proxy(rpi_cam_proxy, None, gp_cam_proxy, cv_cam_proxy)` in camera/__init__.py

Next I miss in base.py the function `preview_configuration` you call in rpi2.py. Maybe my fault, im not so familiar with python.

**Comment by joerno** [comment]
> @CaffeinatedFunctionality @anxuae I made a [fork to support the 64mp arducam ](https://github.com/CollinBardini/pibooth)using the picamera2 library. It works, but I think I can improve the preview performance. If you give it a shot, let me know what you think!

I made it working by changing two lines:
  - "preview_configuration()" was renamed in picamera2 to "create_preview_configuration()"
  - close_proxy(rpi_cam_proxy, gp_cam_proxy, cv_cam_proxy) was missing a parameter -> close_proxy(rpi_cam_proxy, None, gp_cam_proxy, cv_cam_proxy)

**Comment by anxuae** [comment]
Official documentation for `picamera2` : https://datasheets.raspberrypi.com/camera/picamera2-manual-draft.pdf

**Comment by telemarkista** [comment]
> > @CaffeinatedFunctionality @anxuae I made a [fork to support the 64mp arducam ](https://github.com/CollinBardini/pibooth)using the picamera2 library. It works, but I think I can improve the preview performance. If you give it a shot, let me know what you think!
> 
> I made it working by changing two lines:
> 
> * "preview_configuration()" was renamed in picamera2 to "create_preview_configuration()"
> * close_proxy(rpi_cam_proxy, gp_cam_proxy, cv_cam_proxy) was missing a parameter -> close_proxy(rpi_cam_proxy, None, gp_cam_proxy, cv_cam_proxy)
> 
> Now I'm looking for a way to set a fixed focus at camera init. Continous autofocus is not that practicable with little light, I think.

Have you found it? I´ve started using arducam with AF and this would be really handy.

**Comment by joerno** [comment]
> > Now I'm looking for a way to set a fixed focus at camera init. Continous autofocus is not that practicable with little light, I think.
> 
> Have you found it? I´ve started using arducam with AF and this would be really handy.

Yes, there is an example at picamera2: https://github.com/ArduCAM/picamera2_examples/blob/main/Manualfocus_control.py
I changed the line `controls = {'ExposureTime': self.preview_iso*1000}` to `controls = {'ExposureTime': self.preview_iso*1000, 'AfMode': 0, 'LensPosition': 100.0}`
Not the best solution, would be better to get the parameters from the configuration file, but it works.

**Comment by giddyhup** [comment]
@CollinBardini @joerno How did you get the preview working? I use the PR with Bullseye and arducam's 16m autofocus camera (and its drivers) but pibooth fails when it should show the preview (opencv.py returns `Can not get camera preview image`).

**Comment by joerno** [comment]
Sorry I have no experience with the 16m arducam and no idea. does it work if you call `libcamera-still -t 0` like the docs describe?

**Comment by giddyhup** [comment]
> libcamera-still -t 0

I switched to the official Raspberry Camera module V3 and all libcamera-still works.

**Comment by anxuae** [comment]
Ready for test

**Pull request merged**
